# Generated by Django 3.2.14 on 2022-08-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Новость', models.CharField(max_length=150)),
                ('Описание новости', models.TextField(blank=True)),
                ('Дата создания', models.DateTimeField(auto_now_add=True)),
                ('Дата изменения', models.DateTimeField(auto_now=True)),
                ('Фото', models.ImageField(max_length=150, upload_to='photos/%Y/%m/%d/')),
                ('Опубликовано', models.BooleanField(default=True)),
            ],
        ),
    ]
