# Generated by Django 3.2.14 on 2022-08-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Описание новости',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Дата создания',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Опубликовано',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Фото',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Новость',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Дата изменения',
            new_name='updated_at',
        ),
    ]
